#!/bin/bash

set -e
set -o pipefail

image=$(docker build . | tee /dev/tty)
container=$(docker run -d --rm $image sleep 3000)
docker export $container > output/rootfs.tar
docker stop $container

docker build -t $IMAGE_NAME --no-cache ./output
