#!/bin/bash

set -e

docker build -t builder .
docker run --rm -a stdout \
  -v $(pwd)/buildroot:/build/buildroot \
  -v $(pwd)/src:/build/src \
  -v $(pwd)/output:/build/output \
  -v $(pwd)/cache:/build/cache \
  -v $(pwd)/dl:/build/dl \
  builder make PROJECT=toolchain

docker build -t $IMAGE_NAME --no-cache ./output
