#!/bin/bash

set -e

docker build -t base -f Dockerfile.base .
docker run --rm -a stdout -a stderr \
  -v $(pwd)/buildroot:/build/buildroot \
  -v $(pwd)/src:/build/src \
  -v $(pwd)/output:/build/output \
  -v $(pwd)/cache:/build/cache \
  -v $(pwd)/dl:/build/dl \
  base make PROJECT=toolchain
